name: Build and Push Artifacts

on:
  push:
    branches:
      - main  # Trigger on changes to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: logging 
          run : ls

        - name: Checkout code
          uses: actions/checkout@v2

        - name: print something
          run: ls

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '22'

        - name: Install dependencies
          run: npm install  

        - name: build project
          run: npm run build

        - name: Build project
          run: echo "Building the project..."   
          
        - name: Push Artifacts
          run: echo "Pushing build artifacts..."