name: Build and Push Artifacts

on:
  push:
    branches:
      - main  # Trigger on changes to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: logging 
          run : ls

        - name: Checkout code
          uses: actions/checkout@v5

        - name: print something
          run: ls

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '22'
